# Generated by Django 5.0 on 2024-11-02 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('show_time', models.DateTimeField(auto_now=True)),
                ('deadline', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('video', models.FileField(upload_to=None)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_theatre.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_theatre.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_ordered', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('paying_by', models.CharField(choices=[('card', 'Card'), ('cash', 'cash')], max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_theatre.show')),
            ],
        ),
    ]
